Fix pkcs11ca with no cgo compilation bug
Was seeing this bug on my M1 when running `ko build .`, since `PKCS11CA` needs to be redefined for the no-cgo case:

```
../fulcio/pkg/ca/pkcs11ca/pkcs11canocgo.go:26:2: undefined: baseca
```

Signed-off-by: Priya Wadhwa <priya@chainguard.dev>